### ISSUE TITLE
Create a `requirements.txt` with the correct dependencies

### ISSUE THREAD

**Issue by svk014** [Ujjwal-Shekhawat/gstreamer#1]
Unable to install dependencies to run this locally. Please create a `requirements.txt`

**Comment by Ujjwal-Shekhawat** [comment]
I have updated the readme with the instructions to install the required dependencies for GStreamer.

There is no `requirements.txt` for this project as all the bindings and libs required for this are not installed via PyPI. They are all installed via the OS package manager.
